In [ ]:
# Tl;dr
#
# We should try the following for the y-axis of the line chart:
#
# It's 2 lines, and therefore 2 axes.
# Range for the gap line will always be 0-100%, where we plot (100% - Coverage)
#
# For bunches, let n = 70% of max vehicles for the day on a given route, rounded
# down. 0-n is the range of the y-axis for the bunch line.
#
# If it doesn't work, tweak it. Maybe only 40% of max is necessary, and
# in the unlikely case where it's surpassed, the chart can just remain
# pegged at the top.
#
#
#
#
#
#
# Methodology:
#
# The idea is you want a "bad day" or an intraday "bad peak" to fill up
# most of the scale, and a "good day" to run along the bottom of the chart, 
# such that you can intuit quickly what's going on.
#
# If you were to hardcode, say, "30" on the y-axis, but the route never has
# more than 6 vehicles out, "bunch" data will never fill up more than
# 1/5 of the scale. If you just allow peak bunching to dictate
# the scale, the chart will always appear full somewhere, even if you
# have an excellent day on the route, which is visually misleading.

In [ ]:
# Pull a full day's worth of data from our API and store it in df

import requests
import pandas as pd
from time import time
import numpy as np
import json

In [ ]:
url = 'http://sfmta-ds.eba-hqpuyrup.us-east-1.elasticbeanstalk.com/daily-general-json'

In [ ]:
json_data = requests.get(url, params={'day': '2020-05-24'}).json()

In [ ]:
df = pd.DataFrame(data=json_data).sort_values('timestamp')

In [8]:
print(df.shape)
df.head()

(213445, 9)

              timestamp rid   vid  ...  latitude  longitude   direction
0   2020-05-24 00:00:13  38  8641  ...   37.7796   -122.502  38___O_F00
21  2020-05-24 00:00:13  14  8749  ...   37.7512   -122.418  14___I_F00
22  2020-05-24 00:00:13  91  8861  ...   37.7216   -122.475  91___O_N00
23  2020-05-24 00:00:13  91  8639  ...   37.7989   -122.443  91___O_N00
24  2020-05-24 00:00:13  22  8884  ...   37.7607   -122.389  22___I_F00

[5 rows x 9 columns]

In [9]:
# Most-frequently-reported routes

df['rid'].value_counts()

14       19414
NBUS     17186
49       15800
8        15765
1        15727
38       13360
TBUS     11997
24       11486
22       11458
9        10764
14R      10646
LBUS     10325
38R       8849
29        7444
5         7440
19        6620
44        6215
91        3115
25        2694
L_OWL     2331
N_OWL     1756
12        1702
90        1351
Name: rid, dtype: int64

In [10]:
# The most buses out at any one time was 223
df['timestamp'].value_counts()

2020-05-24 16:16:12    223
2020-05-24 16:19:12    223
2020-05-24 16:18:12    223
2020-05-24 16:15:12    223
2020-05-24 14:55:12    222
                      ...
2020-05-24 03:34:13     35
2020-05-24 22:18:12     35
2020-05-24 01:51:12     35
2020-05-24 01:52:12     35
2020-05-24 23:28:12     35
Name: timestamp, Length: 1440, dtype: int64

In [11]:
# 14, NBUS, 49, 8, AND 1 are the heaviest routes

# Let's look at 14 only

df14 = df[df['rid'] == '14']

print(df14.shape)
df14.head()

(19414, 9)

              timestamp rid   vid  ...  latitude  longitude   direction
21  2020-05-24 00:00:13  14  8749  ...   37.7512   -122.418  14___I_F00
30  2020-05-24 00:00:13  14  8868  ...   37.7896   -122.398  14___I_F00
35  2020-05-24 00:00:13  14  8848  ...   37.7774   -122.413  14___O_F00
17  2020-05-24 00:00:13  14  8815  ...   37.7089   -122.453  14___O_F00
1   2020-05-24 00:00:13  14  8738  ...   37.7063   -122.460  14___O_F00

[5 rows x 9 columns]

In [12]:
print(df14['timestamp'].value_counts().max())

18

In [ ]:
# Make a dictionary where each route has its own separate df

uniqueroutes = df.rid.unique()

routedict = {elem : pd.DataFrame() for elem in uniqueroutes}

for key in routedict.keys():
    routedict[key] = df[:][df.rid == key]

In [14]:
routedict

{'1':                   timestamp rid   vid  ...  latitude  longitude   direction
 8119    2020-05-24 03:40:12   1  5805  ...   37.7906   -122.428  1____I_S00
 8157    2020-05-24 03:41:13   1  5805  ...   37.7908   -122.426  1____I_S00
 8195    2020-05-24 03:42:12   1  5805  ...   37.7919   -122.425  1____I_S00
 8233    2020-05-24 03:43:12   1  5805  ...   37.7924   -122.421  1____I_S00
 8271    2020-05-24 03:44:12   1  5805  ...   37.7929   -122.417  1____I_S00
 ...                     ...  ..   ...  ...       ...        ...         ...
 209068  2020-05-24 22:00:12   1  5799  ...   37.7885   -122.437  1____O_S00
 209058  2020-05-24 22:00:12   1  5871  ...   37.7864   -122.454  1____I_E00
 209108  2020-05-24 22:01:12   1  5799  ...   37.7882   -122.440  1____O_S00
 209098  2020-05-24 22:01:12   1  5871  ...   37.7871   -122.448  1____I_E00
 209147  2020-05-24 22:02:12   1  5799  ...   37.7875   -122.446  1____O_S00

 [15727 rows x 9 columns],
 '12':                   timestamp rid   vid  ...  latitude  longitude   direction
 12072   2020-05-24 04:42:12  12  8723  ...   37.7944   -122.405  12___I_S00
 12180   2020-05-24 04:43:12  12  8723  ...   37.7979   -122.406  12___I_S00
 12288   2020-05-24 04:44:12  12  8723  ...   37.7977   -122.408  12___I_S00
 12401   2020-05-24 04:45:12  12  8723  ...   37.7971   -122.413  12___I_S00
 12515   2020-05-24 04:46:12  12  8723  ...   37.7960   -122.421  12___I_S00
 ...                     ...  ..   ...  ...       ...        ...         ...
 197838  2020-05-24 20:08:12  12  8701  ...   37.7970   -122.406  12___I_S00
 197997  2020-05-24 20:09:12  12  8701  ...   37.7963   -122.412  12___I_S00
 198157  2020-05-24 20:10:13  12  8701  ...   37.7961   -122.413  12___I_S00
 198315  2020-05-24 20:11:12  12  8701  ...   37.7957   -122.417  12___I_S00
 198472  2020-05-24 20:12:12  12  8701  ...   37.7953   -122.420  12___I_S00

 [1702 rows x 9 columns],
 '14':                   timestamp rid   vid  ...  latitude  longitude   direction
 21      2020-05-24 00:00:13  14  8749  ...   37.7512   -122.418  14___I_F00
 30      2020-05-24 00:00:13  14  8868  ...   37.7896   -122.398  14___I_F00
 35      2020-05-24 00:00:13  14  8848  ...   37.7774   -122.413  14___O_F00
 17      2020-05-24 00:00:13  14  8815  ...   37.7089   -122.453  14___O_F00
 1       2020-05-24 00:00:13  14  8738  ...   37.7063   -122.460  14___O_F00
 ...                     ...  ..   ...  ...       ...        ...         ...
 213433  2020-05-24 23:59:13  14  8884  ...   37.7856   -122.403  14___I_F00
 213427  2020-05-24 23:59:13  14  8815  ...   37.7062   -122.461  14___I_F00
 213426  2020-05-24 23:59:13  14  8858  ...   37.7551   -122.419  14___O_F00
 213411  2020-05-24 23:59:13  14  8900  ...   37.7932   -122.394  14___O_F00
 213423  2020-05-24 23:59:13  14  8622  ...   37.7277   -122.432  14___O_F00

 [19414 rows x 9 columns],
 '14R':                   timestamp  rid   vid  ...  latitude  longitude   direction
 8138    2020-05-24 03:41:13  14R  6664  ...   37.7322   -122.429  14R__I_F10
 8176    2020-05-24 03:42:12  14R  6664  ...   37.7287   -122.443  14R__I_F10
 8329    2020-05-24 03:46:12  14R  6664  ...   37.7051   -122.468  14R__I_F10
 8959    2020-05-24 04:00:12  14R  6664  ...   37.7069   -122.468        None
 9010    2020-05-24 04:01:12  14R  6664  ...   37.7053   -122.469  14R__I_F10
 ...                     ...  ...   ...  ...       ...        ...         ...
 202249  2020-05-24 20:39:12  14R  6673  ...   37.7930   -122.396  14R__I_F10
 202391  2020-05-24 20:40:12  14R  6642  ...   37.7060   -122.468  14R__O_F10
 202380  2020-05-24 20:40:12  14R  6673  ...   37.7943   -122.395  14R__I_F10
 202522  2020-05-24 20:41:12  14R  6642  ...   37.7068   -122.468        None
 202511  2020-05-24 20:41:12  14R  6673  ...   37.7920   -122.395        None

 [10646 rows x 9 columns],
 '19':                   timestamp rid   vid  ...  latitude  longitude   direction
 8515    2020-05-24 03:50:12  19  8623  ...   37.7429   -122.388  19___I_F00
 8487    2020-05-24 03:50:12  19  8824  ...   37.8064   -122.423        None
 8558    2020-05-24 03:51:12  19  8623  ...   37.7429   -122.388  19___I_F00
 8531    2020-05-24 03:51:12  19  8824  ...   37.8064   -122.423        None
 8603    2020-05-24 03:52:12  19  8623  ...   37.7410   -122.385  19___I_F00
 ...                     ...  ..   ...  ...       ...        ...         ...
 208099  2020-05-24 21:39:12  19  8869  ...   37.7341   -122.379  19___O_F00
 208051  2020-05-24 21:39:12  19  8854  ...   37.8049   -122.424  19___I_F00
 208156  2020-05-24 21:40:12  19  8869  ...   37.7312   -122.374  19___O_F00
 208108  2020-05-24 21:40:12  19  8854  ...   37.8057   -122.421  19___I_F00
 208211  2020-05-24 21:41:12  19  8869  ...   37.7290   -122.367        None

 [6620 rows x 9 columns],
 '22':                   timestamp rid   vid  ...  latitude  longitude   direction
 24      2020-05-24 00:00:13  22  8884  ...   37.7607   -122.389  22___I_F00
 20      2020-05-24 00:00:13  22  8895  ...   37.7869   -122.433  22___I_F00
 16      2020-05-24 00:00:13  22  8655  ...   37.7934   -122.435  22___O_F00
 57      2020-05-24 00:01:13  22  8895  ...   37.7884   -122.434  22___I_F00
 61      2020-05-24 00:01:13  22  8884  ...   37.7607   -122.389  22___I_F00
 ...                     ...  ..   ...  ...       ...        ...         ...
 213362  2020-05-24 23:57:12  22  8822  ...   37.7979   -122.436  22___O_F00
 213393  2020-05-24 23:58:12  22  8749  ...   37.7850   -122.433  22___I_F00
 213398  2020-05-24 23:58:12  22  8822  ...   37.7941   -122.436  22___O_F00
 213429  2020-05-24 23:59:13  22  8749  ...   37.7869   -122.433  22___I_F00
 213434  2020-05-24 23:59:13  22  8822  ...   37.7922   -122.435  22___O_F00

 [11458 rows x 9 columns],
 '24':                   timestamp rid   vid  ...  latitude  longitude   direction
 29      2020-05-24 00:00:13  24  5851  ...   37.7853   -122.440  24___O_N00
 11      2020-05-24 00:00:13  24  5813  ...   37.7396   -122.407  24___I_N00
 66      2020-05-24 00:01:13  24  5851  ...   37.7851   -122.442  24___O_N00
 48      2020-05-24 00:01:13  24  5813  ...   37.7388   -122.407  24___I_N00
 103     2020-05-24 00:02:12  24  5851  ...   37.7861   -122.441  24___O_N00
 ...                     ...  ..   ...  ...       ...        ...         ...
 213346  2020-05-24 23:57:12  24  5807  ...   37.7613   -122.435  24___I_N00
 213403  2020-05-24 23:58:12  24  5788  ...   37.7391   -122.408  24___O_N00
 213382  2020-05-24 23:58:12  24  5807  ...   37.7624   -122.435  24___I_N00
 213439  2020-05-24 23:59:13  24  5788  ...   37.7398   -122.411  24___I_N00
 213418  2020-05-24 23:59:13  24  5807  ...   37.7655   -122.435  24___I_N00

 [11486 rows x 9 columns],
 '25':                   timestamp rid   vid  ...  latitude  longitude   direction
 25      2020-05-24 00:00:13  25  8843  ...   37.7901   -122.395  25___O_N10
 33      2020-05-24 00:00:13  25  8705  ...   37.7898   -122.396  25___O_N10
 62      2020-05-24 00:01:13  25  8843  ...   37.7901   -122.395  25___O_N10
 70      2020-05-24 00:01:13  25  8705  ...   37.7899   -122.397  25___O_N10
 99      2020-05-24 00:02:12  25  8843  ...   37.7901   -122.395  25___O_N10
 ...                     ...  ..   ...  ...       ...        ...         ...
 213345  2020-05-24 23:57:12  25  8901  ...   37.7887   -122.394  25___I_N10
 213376  2020-05-24 23:58:12  25  8811  ...   37.7900   -122.395  25___O_N10
 213381  2020-05-24 23:58:12  25  8901  ...   37.7904   -122.396  25___I_N10
 213417  2020-05-24 23:59:13  25  8901  ...   37.7909   -122.396  25___I_N10
 213412  2020-05-24 23:59:13  25  8811  ...   37.7900   -122.395  25___O_N10

 [2694 rows x 9 columns],
 '29':                   timestamp rid   vid  ...  latitude  longitude   direction
 8364    2020-05-24 03:47:12  29  8739  ...   37.7724   -122.484  29___O_F00
 8431    2020-05-24 03:48:12  29  8806  ...   37.7223   -122.396        None
 8404    2020-05-24 03:48:12  29  8739  ...   37.7772   -122.485  29___O_F00
 8472    2020-05-24 03:49:12  29  8806  ...   37.7228   -122.395        None
 8516    2020-05-24 03:50:12  29  8806  ...   37.7228   -122.395        None
 ...                     ...  ..   ...  ...       ...        ...         ...
 208093  2020-05-24 21:39:12  29  8709  ...   37.7201   -122.406  29___O_F00
 208150  2020-05-24 21:40:12  29  8709  ...   37.7210   -122.403  29___O_F00
 208205  2020-05-24 21:41:12  29  8709  ...   37.7236   -122.402  29___O_F00
 208260  2020-05-24 21:42:12  29  8709  ...   37.7225   -122.396  29___O_F00
 208313  2020-05-24 21:43:12  29  8709  ...   37.7241   -122.395        None

 [7444 rows x 9 columns],
 '38':                   timestamp rid   vid  ...  latitude  longitude   direction
 0       2020-05-24 00:00:13  38  8641  ...   37.7796   -122.502  38___O_F00
 34      2020-05-24 00:00:13  38  8744  ...   37.7883   -122.403  38___O_F00
 14      2020-05-24 00:00:13  38  8740  ...   37.7866   -122.407  38___I_F00
 71      2020-05-24 00:01:13  38  8744  ...   37.7876   -122.405  38___O_F00
 37      2020-05-24 00:01:13  38  8641  ...   37.7792   -122.509  38___O_F00
 ...                     ...  ..   ...  ...       ...        ...         ...
 213378  2020-05-24 23:58:12  38  8629  ...   37.7792   -122.509  38___I_F00
 213377  2020-05-24 23:58:12  38  8722  ...   37.7852   -122.418  38___I_F00
 213442  2020-05-24 23:59:13  38  8801  ...   37.7878   -122.405  38___O_F00
 213413  2020-05-24 23:59:13  38  8722  ...   37.7855   -122.415  38___I_F00
 213414  2020-05-24 23:59:13  38  8629  ...   37.7792   -122.509  38___I_F00

 [13360 rows x 9 columns],
 '38R':                   timestamp  rid   vid  ...  latitude  longitude   direction
 8861    2020-05-24 03:58:12  38R  6679  ...   37.7852   -122.427  38R__I_F01
 8909    2020-05-24 03:59:12  38R  6679  ...   37.7852   -122.427  38R__I_F01
 9224    2020-05-24 04:05:12  38R  6679  ...   37.7833   -122.439  38R__I_F01
 9278    2020-05-24 04:06:12  38R  6679  ...   37.7830   -122.443  38R__I_F01
 9555    2020-05-24 04:11:12  38R  6679  ...   37.7807   -122.472  38R__I_F01
 ...                     ...  ...   ...  ...       ...        ...         ...
 201646  2020-05-24 20:34:12  38R  6614  ...   37.7913   -122.396  38R__I_F01
 201671  2020-05-24 20:34:12  38R  6652  ...   37.7798   -122.492  38R__O_F00
 201806  2020-05-24 20:35:12  38R  6652  ...   37.7796   -122.496  38R__O_F00
 201939  2020-05-24 20:36:12  38R  6652  ...   37.7795   -122.502  38R__O_F00
 202072  2020-05-24 20:37:12  38R  6652  ...   37.7800   -122.507  38R__O_F00

 [8849 rows x 9 columns],
 '44':                   timestamp rid   vid  ...  latitude  longitude   direction
 3       2020-05-24 00:00:13  44  8885  ...   37.7291   -122.419  44___O_N00
 10      2020-05-24 00:00:13  44  8886  ...   37.7402   -122.388  44___O_N00
 40      2020-05-24 00:01:13  44  8885  ...   37.7292   -122.415  44___O_N00
 47      2020-05-24 00:01:13  44  8886  ...   37.7402   -122.388  44___O_N00
 77      2020-05-24 00:02:12  44  8885  ...   37.7313   -122.409  44___O_N00
 ...                     ...  ..   ...  ...       ...        ...         ...
 213337  2020-05-24 23:57:12  44  8641  ...   37.7402   -122.388  44___I_N00
 213402  2020-05-24 23:58:12  44  8832  ...   37.7289   -122.422  44___O_N00
 213373  2020-05-24 23:58:12  44  8641  ...   37.7402   -122.388  44___O_N00
 213438  2020-05-24 23:59:13  44  8832  ...   37.7288   -122.417  44___O_N00
 213409  2020-05-24 23:59:13  44  8641  ...   37.7402   -122.388  44___O_N00

 [6215 rows x 9 columns],
 '49':                   timestamp rid   vid  ...  latitude  longitude   direction
 8697    2020-05-24 03:54:12  49  8701  ...   37.8068   -122.412  49___O_C01
 8745    2020-05-24 03:55:12  49  8701  ...   37.8075   -122.412  49___O_C01
 8702    2020-05-24 03:55:12  49  8722  ...   37.7235   -122.448  49___I_C01
 8792    2020-05-24 03:56:12  49  8701  ...   37.8075   -122.412  49___O_C01
 8839    2020-05-24 03:57:12  49  8701  ...   37.8075   -122.412  49___O_C01
 ...                     ...  ..   ...  ...       ...        ...         ...
 206699  2020-05-24 21:19:12  49  8741  ...   37.7237   -122.438  49___O_C01
 206778  2020-05-24 21:20:12  49  8741  ...   37.7233   -122.442  49___O_C01
 206856  2020-05-24 21:21:12  49  8741  ...   37.7230   -122.445  49___O_C01
 206934  2020-05-24 21:22:12  49  8741  ...   37.7231   -122.447  49___O_C01
 207011  2020-05-24 21:23:12  49  8741  ...   37.7231   -122.451  49___O_C01

 [15800 rows x 9 columns],
 '5':                   timestamp rid   vid  ...  latitude  longitude   direction
 9222    2020-05-24 04:05:12   5  5879  ...   37.7771   -122.443  5____I_S20
 9276    2020-05-24 04:06:12   5  5879  ...   37.7775   -122.440  5____I_S20
 9333    2020-05-24 04:07:12   5  5879  ...   37.7778   -122.439  5____I_S20
 9387    2020-05-24 04:08:12   5  5879  ...   37.7783   -122.435  5____I_S20
 9440    2020-05-24 04:09:12   5  5879  ...   37.7787   -122.431  5____I_S20
 ...                     ...  ..   ...  ...       ...        ...         ...
 205726  2020-05-24 21:08:12   5  5828  ...   37.7748   -122.454  5____O_S20
 205824  2020-05-24 21:09:12   5  5828  ...   37.7745   -122.457  5____O_S20
 205922  2020-05-24 21:10:12   5  5828  ...   37.7740   -122.461  5____O_S20
 206020  2020-05-24 21:11:12   5  5828  ...   37.7753   -122.464  5____O_S20
 206116  2020-05-24 21:12:12   5  5828  ...   37.7773   -122.463  5____O_S20

 [7440 rows x 9 columns],
 '8':                   timestamp rid   vid  ...  latitude  longitude   direction
 9242    2020-05-24 04:05:12   8  6652  ...   37.7173   -122.442  8____I_F00
 9221    2020-05-24 04:05:12   8  6681  ...   37.8011   -122.411  8____O_F00
 9296    2020-05-24 04:06:12   8  6652  ...   37.7156   -122.439  8____I_F00
 9275    2020-05-24 04:06:12   8  6681  ...   37.7997   -122.409  8____O_F00
 9352    2020-05-24 04:07:12   8  6652  ...   37.7144   -122.437  8____I_F00
 ...                     ...  ..   ...  ...       ...        ...         ...
 208069  2020-05-24 21:39:12   8  6676  ...   37.8020   -122.411  8____I_F00
 208126  2020-05-24 21:40:12   8  6676  ...   37.8050   -122.412  8____I_F00
 208182  2020-05-24 21:41:12   8  6676  ...   37.8057   -122.412  8____I_F00
 208237  2020-05-24 21:42:12   8  6676  ...   37.8060   -122.411  8____I_F00
 208291  2020-05-24 21:43:12   8  6676  ...   37.8070   -122.407        None

 [15765 rows x 9 columns],
 '9':                   timestamp rid   vid  ...  latitude  longitude   direction
 8971    2020-05-24 04:00:12   9  8714  ...   37.7103   -122.410  9____I_N10
 9023    2020-05-24 04:01:12   9  8714  ...   37.7093   -122.407  9____I_N10
 9076    2020-05-24 04:02:12   9  8714  ...   37.7089   -122.405  9____I_N10
 9130    2020-05-24 04:03:12   9  8714  ...   37.7121   -122.403  9____I_N10
 9183    2020-05-24 04:04:12   9  8714  ...   37.7125   -122.402  9____I_N10
 ...                     ...  ..   ...  ...       ...        ...         ...
 207127  2020-05-24 21:25:12   9  8723  ...   37.7067   -122.413  9____O_N10
 207200  2020-05-24 21:26:12   9  8723  ...   37.7087   -122.420  9____O_N10
 207271  2020-05-24 21:27:12   9  8723  ...   37.7123   -122.418  9____O_N10
 207342  2020-05-24 21:28:12   9  8723  ...   37.7143   -122.425        None
 208427  2020-05-24 21:46:12   9  8723  ...   37.7138   -122.423        None

 [10764 rows x 9 columns],
 '90':                   timestamp rid   vid  ...  latitude  longitude   direction
 28      2020-05-24 00:00:13  90  8624  ...   37.7099   -122.404  90___I_N01
 4       2020-05-24 00:00:13  90  8853  ...   37.7814   -122.421  90___O_N00
 6       2020-05-24 00:00:13  90  8901  ...   37.7733   -122.416  90___I_N01
 65      2020-05-24 00:01:13  90  8624  ...   37.7099   -122.404  90___I_N01
 41      2020-05-24 00:01:13  90  8853  ...   37.7795   -122.420  90___O_N00
 ...                     ...  ..   ...  ...       ...        ...         ...
 213395  2020-05-24 23:58:12  90  8834  ...   37.7100   -122.404  90___I_N01
 213405  2020-05-24 23:58:12  90  8644  ...   37.7690   -122.408  90___I_N01
 213430  2020-05-24 23:59:13  90  8834  ...   37.7100   -122.404  90___I_N01
 213431  2020-05-24 23:59:13  90  8652  ...   37.7731   -122.418  90___O_N00
 213441  2020-05-24 23:59:13  90  8644  ...   37.7695   -122.410  90___I_N01

 [1351 rows x 9 columns],
 '91':                   timestamp rid   vid  ...  latitude  longitude   direction
 22      2020-05-24 00:00:13  91  8861  ...   37.7216   -122.475  91___O_N00
 23      2020-05-24 00:00:13  91  8639  ...   37.7989   -122.443  91___O_N00
 31      2020-05-24 00:00:13  91  8614  ...   37.7726   -122.474  91___I_N00
 32      2020-05-24 00:00:13  91  8832  ...   37.7460   -122.387  91___O_N00
 36      2020-05-24 00:00:13  91  8715  ...   37.7230   -122.453  91___I_N00
 ...                     ...  ..   ...  ...       ...        ...         ...
 213416  2020-05-24 23:59:13  91  8635  ...   37.7216   -122.475  91___O_N00
 213419  2020-05-24 23:59:13  91  8865  ...   37.7788   -122.393  91___I_N00
 213420  2020-05-24 23:59:13  91  8611  ...   37.7307   -122.471  91___O_N00
 213422  2020-05-24 23:59:13  91  8879  ...   37.7176   -122.442  91___I_N00
 213444  2020-05-24 23:59:13  91  8715  ...   37.8003   -122.447  91___I_N00

 [3115 rows x 9 columns],
 'LBUS':                   timestamp   rid   vid  ...  latitude  longitude   direction
 9873    2020-05-24 04:16:12  LBUS  8889  ...   37.7356   -122.504        None
 9936    2020-05-24 04:17:12  LBUS  8889  ...   37.7362   -122.504        None
 10003   2020-05-24 04:18:12  LBUS  8889  ...   37.7414   -122.505  LBUS_I_F00
 10071   2020-05-24 04:19:13  LBUS  8889  ...   37.7420   -122.500  LBUS_I_F00
 10143   2020-05-24 04:20:12  LBUS  8889  ...   37.7422   -122.496  LBUS_I_F00
 ...                     ...   ...   ...  ...       ...        ...         ...
 207515  2020-05-24 21:30:12  LBUS  8857  ...   37.7425   -122.490  LBUS_O_F00
 207580  2020-05-24 21:31:12  LBUS  8857  ...   37.7422   -122.496  LBUS_O_F00
 207644  2020-05-24 21:32:12  LBUS  8857  ...   37.7420   -122.501  LBUS_O_F00
 207708  2020-05-24 21:33:12  LBUS  8857  ...   37.7399   -122.505  LBUS_O_F00
 207773  2020-05-24 21:34:12  LBUS  8857  ...   37.7382   -122.501  LBUS_O_F00

 [10325 rows x 9 columns],
 'L_OWL':                   timestamp    rid   vid  ...  latitude  longitude   direction
 26      2020-05-24 00:00:13  L_OWL  8636  ...   37.7362   -122.504  L____I_N00
 19      2020-05-24 00:00:13  L_OWL  8816  ...   37.7802   -122.413  L____I_N00
 27      2020-05-24 00:00:13  L_OWL  8835  ...   37.7361   -122.505  L____O_N00
 5       2020-05-24 00:00:13  L_OWL  8654  ...   37.7807   -122.412  L____O_N00
 7       2020-05-24 00:00:13  L_OWL  8743  ...   37.8069   -122.421  L____O_N00
 ...                     ...    ...   ...  ...       ...        ...         ...
 213437  2020-05-24 23:59:13  L_OWL  8614  ...   37.7778   -122.416  L____O_N00
 213440  2020-05-24 23:59:13  L_OWL  8732  ...   37.7361   -122.504  L____I_N00
 213443  2020-05-24 23:59:13  L_OWL  8744  ...   37.7689   -122.427  L____I_N00
 213415  2020-05-24 23:59:13  L_OWL  8880  ...   37.7380   -122.505  L____O_N00
 213425  2020-05-24 23:59:13  L_OWL  8720  ...   37.8076   -122.417  L____O_N00

 [2331 rows x 9 columns],
 'NBUS':                   timestamp   rid   vid  ...  latitude  longitude   direction
 8439    2020-05-24 03:49:12  NBUS  8810  ...   37.7601   -122.509        None
 8480    2020-05-24 03:50:12  NBUS  8810  ...   37.7602   -122.509        None
 8524    2020-05-24 03:51:12  NBUS  8810  ...   37.7602   -122.509        None
 8567    2020-05-24 03:52:12  NBUS  8810  ...   37.7602   -122.509        None
 8612    2020-05-24 03:53:12  NBUS  8810  ...   37.7602   -122.509        None
 ...                     ...   ...   ...  ...       ...        ...         ...
 208598  2020-05-24 21:49:12  NBUS  8660  ...   37.7601   -122.509  NBUS_O_F00
 208643  2020-05-24 21:50:12  NBUS  8660  ...   37.7601   -122.509  NBUS_O_F00

In [15]:
# Print each Route ID and its max vehicles out for the day

for key, value in routedict.items():
  print("Route ID: ", key)
  print(value['timestamp'].value_counts().max())

Route ID:  38
17
Route ID:  14
18
Route ID:  91
7
Route ID:  22
12
Route ID:  25
4
Route ID:  L_OWL
5
Route ID:  90
3
Route ID:  24
11
Route ID:  N_OWL
4
Route ID:  44
7
Route ID:  1
22
Route ID:  14R
16
Route ID:  29
9
Route ID:  NBUS
18
Route ID:  19
8
Route ID:  TBUS
15
Route ID:  49
20
Route ID:  38R
11
Route ID:  9
13
Route ID:  8
20
Route ID:  5
9
Route ID:  LBUS
13
Route ID:  12
2

In [ ]:
# 22 was the max for this day. Route 1.
#
# Once Covid is over, maybe you'll get 30-35 on a route.
#
# Remember that the line plots bunches at each snapshot, so the most there can 
# be is n - 1 bunches at a time (n = number of buses out).

# For Route 1 you're looking at 22 * 0.7 = 15.4 --> 15 (0-15 y-axis range)
# For Route 91 it would be 7 * 0.7 = 4.9 --> 4 (0-4 y-axis range)

# The ideal graph is one where a bad day has big spikes and uses up
# most of the scale, while a good day stays near the bottom.